routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role']], function() {
	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('users', 'Admin\UserController', ['except' => [ 'show' ]]);
	Route::resource('roles', 'Admin\RoleController', ['except' => [ 'show' ]]);
    Route::get('change-password', 'Admin\UserController@getChangePassword')->name('getChangePassword');
    Route::post('change-password', 'Admin\UserController@postChangePassword')->name('postChangePassword');
});

/*
 * Route for testing
 */
Route::get('/test/user', 'Admin\TestController@user');
Route::post('/test/user', 'Admin\TestController@user');
Route::resource('/test', 'Admin\TestController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Role;
use Auth;
class User extends Authenticatable
{

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    public function role()
    {
        return $this->belongsTo(Role::class, 'role_id');
    }

    public function hasPermission($actionName)
    {
        if (isNoneAuthorizeAction($actionName))
            return true;
        
        if ($this->role->id == config("constants.SUPERADMIN_ROLE_ID"))
            return true;
        $permissions = $this->role['permissions'];
        return in_array($actionName, $permissions);
    }
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Http\Responses\APIResponse;
use Validator,Hash,Auth;

class UserController extends Controller
{
    public function index(Request $request){
        $keyword = $request->input('keyword','');
        $limit = (int)$request->input('limit',config("constants.ITEM_PER_PAGE"));
        $query = User::query();
        if(!empty($keyword)){
            $query->where(function($query)use($keyword){
            	$query->where("name","like","%$keyword%")
            	->orwhere("email","like","%$keyword%");
            });
        }
        $user = $query->paginate($limit);
        return APIResponse::success(compact('user'));
    }

    public function create(){
        $role = Role::all();
        return APIResponse::success(compact('role'));
    }

    public function store(Request $request){
        $validator = Validator::make($request->all(), [
            'email' => 'required|string|email|max:191|unique:users,email',
            'password'=> 'required|max:191|min:6',
            'name' => 'required|max:191',
            'role_id' => 'required'
        ]);
        if ($validator->fails()) {
            return APIResponse::fail([],$validator->errors()->first());
        }
        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $user = User::create($data);
        return APIResponse::success(compact('user'));
    }

    public function edit(User $user){
        $role =  Role::all();
        return APIResponse::success(compact('role','user'));
    }

    public function update(Request $request,User $user){
        $data = $request->only(['name','email','role_id']);
        $validator = Validator::make($data, [
            'email' => 'required|string|email|max:191|unique:users,email,'.$user->id,
            'name' => 'required|max:191',
            'role_id' => 'required'
        ]);
        if ($validator->fails()) {
            return APIResponse::fail([],$validator->errors()->first());
        }
        $user->update($data);
        return APIResponse::success(compact('user'));
    }

    public function destroy(User $user)
    {
        if (Auth::user()->id == $user->id) {
            return APIResponse::fail([],'You can\'t delete yourself!');
        }
        $user->delete();
        return APIResponse::success([],'Delete user successfully!');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\User;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Validator, Hash, Excel;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        
        $q = trim(urldecode($request->input('q')));
        $query = User::latest();
        if ($q) {
            $query->where('email', 'LIKE', "%" . $q . "%")
                ->orWhere('name', 'LIKE', "%" . $q . "%");
        }
        if($request->get('export')){
            $type =$request->get('export');
            $items = $query->get();
            $captions = ['Id', 'Name', 'Email', 'Created at', 'Updated at'];
            export($items, $captions, $type,'List_User', 'sheet1');
            return back();
        }
        
        $items = $query->paginate(config("constants.ITEM_PER_PAGE"));
        return view('admin.users.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name', 'id');
        return view('admin.users.form', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserCreateRequest $request)
    {

        try {
            User::create([
                'email' => $request->input("email"),
                'name' => $request->input("name"),
                'role_id' => $request->input("role_id"),
                'password' => bcrypt('123123123'),
            ]);
        } catch (\Exception $e) {
            flash($e->getMessage(), 'danger');
            return back()->withInput();
        }

        flash('Add user successfully!', 'success');
        return redirect(route('users.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::pluck('name', 'id');
        return view('admin.users.form', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserUpdateRequest $request
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update($request->all());

        flash('Update user successfully!', 'success');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        if (Auth::user()->id == $user->id) {
            flash('You can\'t delete yourself!', 'danger');
            return back();
        }

        $user->delete();
        flash('Delete user successfully!', 'success');
        return redirect(route('users.index'));
    }

    public function getChangePassword()
    {
        return view('auth.passwords.chang_password');

    }
    public function postChangePassword(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'old_password'=> 'required|string|min:6',
            'new_password' => 'required|string|min:6',
            'confirm_password' => 'required|string|min:6|same:new_password'
        ]);
        if($validator->fails()){
            return back()->withErrors($validator);
        }

        $current_password = Auth::User()->password;
        if(!Hash::check($data['old_password'], $current_password)){
            flash('Please enter correct old password', 'danger');
            return back();
        }
        $user_id = Auth::User()->id;                       
        $obj_user = User::find($user_id);
        $obj_user->password = Hash::make($data['new_password']);;
        $obj_user->save();
        flash('Change password successfully!', 'success');
        return redirect(route('home'));
    }
}

resources/views/admin/users/form.blade.php
@extends('admin.layouts.app')
@if (!empty($user))
    @section('title','Edit User')
@else
   @section('title','Add User')
@endif
@section('content')
    <div class="box news-form">
        <div class="box-header with-border">
              <h3 class="box-title">@yield('title')</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    @if (!empty($user))
                    {!! Form::model($user, ['method' => 'PATCH', 'route' => ['users.update', $user->id]]) !!}
                    @else
                    {!! Form::open(['route' => ['users.store']]) !!}
                    @endif

                    <div class="form-group">
                        {!! Form::label('email', 'Email') !!}
                        @if (!empty($user))
                            {!! Form::email('email', null, ['readonly' => 'readonly', 'class' => 'form-control', 'placeholder' => "Email"]) !!}
                        @else
                            {!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => "Email"]) !!}
                        @endif
                    </div>

                    <div class="form-group">
                        {!! Form::label('name', 'Name') !!}
                        {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => "Name"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('role_id', 'Role') !!}
                        {!!Form::select('role_id', $roles, !empty($user) ? $user->role->id : null, ['class' => 'form-control'])!!}
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-2 margin-b-5">{!! Form::submit('Save', ['class' => 'btn btn-primary form-control']) !!}</div>
                            <div class="col-sm-2 margin-b-5"><a href="{{ route("users.index") }}" class="btn btn-primary form-control">Back</a></div>
                        </div>
                    </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('title','List User')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box post-list">
                <div class="box-header with-border">
                      <h3 class="box-title">@yield('title')</h3>
                </div>
                <div class="box-body">
                    <form method="GET" class="form-inline">
                        <div class="form-group">
                            {!! Form::label('q', 'Search: ') !!}
                            {!! Form::text('q', Request::get('q'), ['class' => 'form-control', "placeholder" => "Email or name"]) !!}
                        </div>
                        <button class="btn btn-primary" type="submit"> <i class="fa fa-search"></i> Search</button>
                        <button class="btn btn-success" name="export" value="xls" type="submit">Export</button>
                    </form>

                    <hr>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Created at</th>
                                <th>Updated at</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($items as $item)
                                <tr>
                                    <td>{{$item->id}}</td>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->email}}</td>
                                    <td>{{$item->role->name}}</td>
                                    <td>{{$item->created_at}}</td>
                                    <td>{{$item->updated_at}}</td>
                                    <td>
                                        @hasPermission('users.edit')
                                        <a href="{{ route("users.edit", $item->id) }}" class="btn btn-warning"><i class="fa fa-pencil"></i> Edit</a>
                                        @endhasPermission
                                        @hasPermission('users.destroy')
                                        <button class="btn btn-danger delete-item" data-form="form-delete-{{$item->id}}"><i class="fa fa-trash"></i> Delete</button>
                                        {!! Form::open(['method' => 'DELETE', 'id' => "form-delete-" . $item->id, 'route' => ['users.destroy', $item->id]]) !!}
                                        {!! Form::close() !!}
                                        @endhasPermission
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    @if($items)
                        {!!$items->appends(request()->except('page'))->render()!!}
                    @endif
                    @hasPermission('roles.create')
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="{{ route("users.create") }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Create user</a>
                        </div>
                    </div>
                    @endhasPermission
                </div>
            </div>
        </div>
    </div>
@endsection